version: '3.9'

services:
  lobby-service:
    build: ./
    image: jackal-game-client
    container_name: jackal_game-client
    ports:
      - "3000:3000"
    environment:
      REACT_APP_VK_CLIENT_ID: ${REACT_APP_VK_CLIENT_ID}
      REACT_APP_YANDEX_CLIENT_ID: ${REACT_APP_YANDEX_CLIENT_ID}
      REACT_APP_ENTERPRISE_URL: ${REACT_APP_ENTERPRISE_URL}
      REACT_APP_LOBBY_SERVICE_URL: ${REACT_APP_LOBBY_SERVICE_URL}
      REACT_APP_GAME_SERVICE_URL: ${REACT_APP_GAME_SERVICE_URL}
    restart: always